### ISSUE TITLE
Accesses are not ordered

### ISSUE THREAD

**Issue by VincentBlondeau** [feenkcom/jdt2famix#11]
When defining accesses in a method, there should an order between them.
That is defined through the FAMIXAssociation next and previous methods.

E.g.:
myMethod(){
  var1.m1();
  var2.m2();
}

defines 2 accesses : (A1)myMethod -> m1 and (A2)myMethod -> m2 with A1.next = A2 and A2.previous = A1

**Comment by girba** [comment]
I did not populate this information because I never saw a real case where we needed it. Do you have a specific case where you do need it?

In any case, I will look into it.

**Comment by VincentBlondeau** [comment]
I don't have a specific case where I need it. But, I prefer to log this before I forget. Moreover, it makes a list of the possible enhancements ;)

**Comment by girba** [comment]
We can reopen this if we have a concrete case.
