### ISSUE TITLE
Export must be in UTF-8

### ISSUE THREAD

**Issue by girba** [feenkcom/jdt2famix#20]
On Windows, the export is not in UTF-8 and this causes problems when loading into Moose.

**Comment by willy-juisan** [comment]
I also encounter this issue @girba, and have opened issue in moose repo..

**Comment by fuhrmanator** [comment]
I found some concrete cases with [ArgoUML 0.28.1](http://argouml-downloads.tigris.org/argouml-0.28.1/) where Java comments and Strings with author's names aren't consistently encoded, and I think this is a special case for jdt2famix with UTF. 

Some accented characters are in ANSI (? it's a single byte accent character), while others appear to be two-byte. Perhaps it's not possible to properly encode them, but at least the MSE should not contain invalid UTF8 (which causes errors on import in Moose).

To find the accent cases in ArgoUML 0.28.1, search for the names:

- Christian (as in Christian López Espánola)
- Oliveira (as in Luís Sérgio Oliveira)
- Marcos (as in Marcos Aurélio)

Here's an incomplete list of cases (the files have the real character values; I copied them from VS Code; don't trust what's pasted here; it is just to give you an idea):

- /src/argouml/sr​c/argouml-app/src/org/argouml/ui/Abo​utBox.java:246 vs :277

        buf.append("+ Sequence Diagrams: Christian L�pez Esp�nola\n");

        buf.append("+ Christian L��pez Esp��nola\n");

- /src/argouml/sr​c/argouml-app/src/org/argouml/profile\FormatingStrategy.java:33 (:29-:34)

        /**
         * Interface for the formating strategy to be used when formating model element
         * names.
         * 
         * @author Marcos Aur�lio
         */

**Comment by fuhrmanator** [comment]
Here are two work-arounds for Windows 10 (for the MSE file generated by jdt2famix 1.0.3 on ArgoUML 0.28.1 shown above):

- use Notepad++ to open the .MSE file as ANSI (you may have to change Notepad++ > Settings > Preferences > New Document > Encoding > ANSI) and then use Encoding > Convert to UTF-8, then save the file.  

- If you're running GitBash (I think that's where I got this...), you might be able to use `iconv`:

        iconv -f CP1252 -t UTF-8 ArgoUML-0-28-1.mse > ArgoUML-0-28-1_UTF-8.mse

**Comment by fuhrmanator** [comment]
Another possible solution is to specify `java -Dfile.encoding=UTF-8 ...` as stated in https://stackoverflow.com/a/35135497/1168342 (there's also some suggestions on how to create the `FileWriter` forcing UTF-8 inside the Java code).
